# Utilise l'image Node.js légère basée sur Alpine Linux
FROM node:alpine

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Copier les fichiers de gestion des dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port utilisé par Vite
EXPOSE 5173

# Démarrer l'application en mode développement
CMD ["npm", "run", "dev"]
