services:
  app:
    container_name: fab-call-website-dev-c
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: fabcallot/fab-call-website:dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
