version: '3.8'
services:
  client:
    image: fab-call-website-i
    build:
      dockerfile: Dockerfile.prod
    container_name: fab-call-website-c
    ports:
      - "9090:80"
      - "9090:443"
    environment:
      - NODE_ENV=production

