services:
  client:
    image: fab-call-website-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: fab-call-website-dev-c
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules/
    ports:
      - "3080:3080"
    environment:
      - NODE_ENV=developement
volumes:
  node_modules:

