services:
  client:
    image: fabcallot/fab-call-website:latest
    build:
      dockerfile: Dockerfile.prod
    container_name: fab-call-website-c
    ports:
      - "9090:80"
    environment:
      - NODE_ENV=production

