# name: pipeline
# on:
#   push:
#     branches:
#       - 'main'
# jobs:
#   deploy:
#     name: build && push image to docker hub
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           ref: 'main'
    
#       - name: setup docker buildx
#         uses: docker/setup-buildx-action@v2
    
#       - name: docker login
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#       - name: build and push api
#         id: build-push-api
#         uses: docker/build-push-action@v3
#         with:
#           context: .
#           file: Dockerfile.prod
#           push: true
#           tags: fabcallot/fab-call-website:latest

name: pipeline
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    name: build && push image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
    
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
    
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: fabcallot/fab-call-website:latest

