name: pipeline

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Build and Push Images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Production Image
        id: build-push-prod
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: fabcallot/fab-call-website:latest

      - name: Build and Push Development Image
        id: build-push-dev
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.dev
          push: true
          platforms: linux/amd64,linux/arm64
          tags: fabcallot/fab-call-website-dev:latest
