name: PR Testing Pipeline

on:
  pull_request:
    branches:
      - "*"  # Déclenche sur toutes les branches PR

jobs:
  test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install
          
      - name: Build Application
        run: |
          npm run build

      - name: Start Application
        run: |
          npm run preview > preview.log 2>&1 &
          sleep 5  # Attendre que l'application démarre

      - name: Download ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
          && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | tee /etc/apt/sources.list.d/ngrok.list \
          && apt update && apt install -y ngrok

      - name: Expose Application via ngrok
        run: |
          ngrok http 4173 > ngrok.log &  # Change le port si nécessaire
          sleep 5
          echo "TEST_URL=$(curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')" >> $GITHUB_ENV

      - name: Post Test URL in PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const url = process.env.TEST_URL;
            const prNumber = context.payload.pull_request.number;
            const message = `Tests passed! You can view the test URL here: ${url}`;
            await github.issues.createComment({
              ...context.repo,
              issue_number: prNumber,
              body: message,
            });

      - name: Stop Application
        run: |
          kill $(lsof -t -i:4173)  # Change le port si nécessaire
